# Generated by Django 4.1.1 on 2022-11-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_hotelbooking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='user',
        ),
    ]
