# Generated by Django 4.1.4 on 2022-12-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_booking_booking_type_booking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
