# Generated by Django 4.1.1 on 2022-12-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_hotel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='people_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='room_count',
            field=models.IntegerField(default=1),
        ),
    ]
